server:
  port: 9099

spring:
  application:
    name: AuthService
  datasource:
    url: jdbc:mysql://localhost:3306/authservice
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true