server:
  port: 9099

spring:
  application:
    name: AuthorizationService

  data:
    mongodb:
      database: UserService


      # uri: mongodb+srv://shyam130701:shyam@shyamcluster.wfbvgmu.mongodb.net/MovieService
      host: localhost
      port: 27017
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: localhost:9092
    admin:
      properties:
        bootstrap.servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: auth-groupId
      bootstrap-servers: localhost:9092